Update bootstrap to install stylua and add default config

diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -56,13 +56,74 @@ install_packages_linux() {
     sudo apt-get install -y tmux direnv fzf ripgrep zsh
 }
 
+install_brew_mac() {
+    if ! command -v brew >/dev/null; then
+        echo "Homebrew not found. Installing..."
+        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
+    fi
+}
+
 install_packages_mac() {
-    brew install tmux direnv frum fzf go pyenv ripgrep rust zsh
+    brew install tmux direnv frum fzf go pyenv ripgrep zsh
+}
+
+install_rustup_mac() {
+    if ! command -v rustup >/dev/null; then
+        echo "Installing Rust using rustup..."
+        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
+        source "$HOME/.cargo/env"
+        rustup default nightly
+    else
+        echo "Rustup is already installed."
+    fi
+}
+
+install_nvm_mac() {
+    if ! command -v nvm >/dev/null; then
+        echo "Installing NVM..."
+        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.3/install.sh | bash
+        export NVM_DIR="$HOME/.nvm"
+        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
+    else
+        echo "NVM is already installed."
+    fi
+}
+
+install_uv_mac() {
+    if ! command -v uv >/dev/null; then
+        echo "Installing UV..."
+        curl -LsSf https://astral.sh/uv/install.sh | sh
+    else
+        echo "UV is already installed."
+    fi
+}
+
+# Note: Must be run after installing UV
+install_ruff_mac() {
+    if ! command -v ruff >/dev/null; then
+        echo "Installing Ruff..."
+        uv tool install ruff@latest
+    else
+        echo "Ruff is already installed."
+    fi
+}
+
+install_formatters_mac() {
+    if ! command -v stylua >/dev/null; then
+        echo "Installing stylua..."
+        cargo install stylua
+    else
+        echo "stylua is already installed."
+    fi
 }
 
 if [ "$OS" = "mac" ]; then
     install_nvim_mac
+    install_brew_mac
     install_packages_mac
+    install_rustup_mac
+    install_nvm_mac
+    install_uv_mac
     ZSH_PATH="$(which zsh)"
 else
     export SUDO_ASKPASS=/bin/true
